ARG BASE_CONTAINER=jupyter/datascience-notebook:latest
FROM $BASE_CONTAINER
# USER root

RUN pip install \
	'dm-sonnet==2.0.0' \
	'kipoiseq==0.5.2'\	
	'numpy'\
	'pandas'\
	'tensorflow'\
	'tensorflow-hub==0.11.0'